export const GET_ALL_CONTACTS = "GET_ALL_CONTACTS";
export const GET_ALL_CONTACTS_SUCCED = "GET_ALL_CONTACTS_SUCCED";
export const GET_ALL_CONTACTS_FAILD = "GET_ALL_CONTACTS_FAILD";

export const GET_US_CONTACTS = "GET_US_CONTACTS";
export const GET_US_CONTACTS_SUCCED = "GET_US_CONTACTS_SUCCED";
export const GET_US_CONTACTS_FAILD = "GET_US_CONTACTS_FAILD";